### ISSUE TITLE
Add statistics

### ISSUE THREAD

**Issue by neongreen** [juspay/fencer#101]
(will expand later)

**Comment by mdimjasevic** [comment]
Here is a branch for the issue: https://github.com/juspay/fencer/tree/mdimjasevic/101-stats-support

**Comment by neongreen** [comment]
Can you make a draft PR? It's nice when I can look at PRs and see everything-in-progress plus get an idea of how far the things are going

**Comment by mdimjasevic** [comment]
> Can you make a draft PR? It's nice when I can look at PRs and see everything-in-progress plus get an idea of how far the things are going

Definitely! The PR is here: https://github.com/juspay/fencer/pull/109
