### ISSUE TITLE
Document all env vars, including logging vars

### ISSUE THREAD

**Issue by neongreen** [juspay/fencer#11]

**Comment by neongreen** [comment]
For env vars, see `Fencer.Settings`. For logging env vars, see https://gitlab.com/twittner/tinylog/blob/develop/src/System/Logger.hs#L117-120.

**Comment by mdimjasevic** [comment]
@neongreen , is the link in your comment to say that there are three logging environment variables, namely `LOG_BUFFER`, `LOG_LEVEL` and `LOG_NETSTR`?

For environment variables, based on the `Fencer.Settings`, I suppose they're `RUNTIME_ROOT`, `RUNTIME_SUBDIRECTORY` and `RUNTIME_IGNOREDOTFILES`.

Please correct me if I'm wrong or if I'm missing any.

**Comment by neongreen** [comment]
> is the link in your comment to say that there are three logging environment variables, namely LOG_BUFFER, LOG_LEVEL and LOG_NETSTR?

Right.

> For environment variables, based on the Fencer.Settings, I suppose they're RUNTIME_ROOT, RUNTIME_SUBDIRECTORY and RUNTIME_IGNOREDOTFILES.

Also right.

**Comment by mdimjasevic** [comment]
I forgot to mention the `LOG_LEVEL_MAP` logging variable: https://gitlab.com/twittner/tinylog/blob/develop/src/System/Logger.hs#L120.
