### ISSUE TITLE
Build and publish a Docker image for Fencer

### ISSUE THREAD

**Issue by neongreen** [juspay/fencer#18]

**Comment by neongreen** [comment]
Also see https://github.com/lyft/ratelimit/issues/57.

**Comment by neongreen** [comment]
Let's push to GitHub package registry, and perhaps switch to Dockerhub later.

**Comment by neongreen** [comment]
Done.

**Comment by neongreen** [comment]
Actually no. We still need usage instructions for Docker in the README. Also, I wonder: is it possible to get an image corresponding to a specific commit?

**Comment by mdimjasevic** [comment]
Are you asking if it is possible to get an image from the CI corresponding to a specific commit in the Fencer repository? With Git you can get that specific commit and once the image is built, it'd have to be pushed/published somewhere.

**Comment by neongreen** [comment]
I mean something like "an external developer should be able to say `docker run juspay/fencer:03a8cf0d`", because `docker run juspay/fencer:master` is ambiguous.

We can probably get this by tagging all images with commit hashes in addition to `:master`.

**Comment by neongreen** [comment]
I am going to do this one.
