### ISSUE TITLE
Ensure that Fencer.Proto does not go out of date

### ISSUE THREAD

**Issue by neongreen** [juspay/fencer#58]
Currently Fencer/Proto.hs is generated from a protobuf file in the repo. It also depends on proto3-suite. So, when updating the version of proto3-suite we might forget to rerun `compile-proto-file` – this just happened to me, for instance.

Possible solutions:

1. Do nothing.
2. Don't check Fencer/Proto.hs into the repo, always generate it during the build.
3. Check Fencer/Proto.hs into the repo but error out during the build if the generated file differs.

**Comment by mdimjasevic** [comment]
@neongreen said in a private correspondence: "It would also be nice if the script that generates the file was abstracted into an .sh file or something and then the README would refer to that file."
