### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by mdimjasevic** [juspay/fencer#88]
Set up the Travis continuous integration for Fencer:

- [ ] Add a `.travis.yml` file,
- [ ] port secrets from GitLab CI settings. Variables should be encrypted and store in the `.travis.yml` file and should be only made available to jobs that actually require them,
- [ ] Consult the [Travis CI documentation](https://docs.travis-ci.com/user/languages/nix/) to see how to support Nix.

**Comment by mdimjasevic** [comment]
@neongreen, I created a branch for this issue: [mdimjasevic/88-travis-ci](https://github.com/juspay/fencer/tree/mdimjasevic/88-travis-ci).

**Comment by neongreen** [comment]
OK, open a PR when there's something to review.
